# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack Misteli's page
email: canyoufindme?@jmisteli.com
description: > # this means to ignore newlines until "baseurl:"
 I wonder what will happen here...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jmisteli.com" # the base hostname & protocol for your site
twitter_username: JackMisteli
github_username:  Otomakan

# Build settings
markdown: kramdown
